/*
 * yamlTemplate.cpp
 *
 * The default COMPAS YAML template - a vector of strings, one per line,
 * that MakeYAMLfile uses when no template file is supplied (or when the
 * supplied file can't be read).
 *
 * This file is intentionally near-empty: a single data literal wrapped in
 * the yaml namespace. It is split from yaml.cpp so that:
 *
 *   - the template (which grows as new COMPAS options are added) can be
 *     edited without scrolling through yaml.cpp's parsing logic;
 *   - editing the template only forces this TU to recompile, not yaml.cpp;
 *   - yaml.cpp's logic is correspondingly easier to navigate.
 *
 * yaml.h declares this symbol as:
 *     extern const std::vector<std::string> yamlTemplate;
 * and is included below so the definition inherits external linkage from
 * the declaration (without the include, namespace-scope `const` defaults
 * to internal linkage and yaml.cpp's TU would fail to find the symbol at
 * link time).
 *
 * To add or modify entries: edit the literal below. Each std::string
 * corresponds to one line in the generated YAML file.
 */

#include "yaml.h"

namespace yaml {

    // The default COMPAS YAML template. Used by MakeYAMLfile when no
    // template file is supplied (or when the supplied file can't be read).
    // Defined here (rather than in the header) so there is exactly one
    // definition in the program, regardless of how many TUs include yaml.h.
    const std::vector<std::string> yamlTemplate {
        "",
            "booleanChoices:",
            "",
            "    ### LOGISTICS",
            "    --debug-to-file",
            "    --detailed-output                                               # WARNING! this creates a data heavy file",
            "    --emit-gravitational-radiation",
            "    --enable-warnings                                               # option to enable/disable warning messages",
            "    --errors-to-file",
            "    --evolve-main-sequence-mergers",
            "    --evolve-unbound-systems",
            "    --population-data-printing",
            "    --print-bool-as-string",
            "    --quiet",
            "    --rlof-printing",
            "    --store-input-files",
            "    --switch-log",
            "",
            "    ### STELLAR PROPERTIES",
            "    --check-photon-tiring-limit",
            "    --enable-rotationally-enhanced-mass-loss",
            "    --enhance-CHE-lifetimes-luminosities",
            "    --expel-convective-envelope-above-luminosity-threshold",
            "    --natal-kick-for-PPISN",
            "    --scale-CHE-mass-loss-with-surface-helium-abundance",
            "",
            "    ### BINARY PROPERTIES",
            "    --allow-touching-at-birth                                       # record binaries that have stars touching at birth in output files",
            "    --include-WD-binaries-as-DCO                                    # record WD binaries in the BSE DCO file",
            "",
            "    ### MASS TRANSFER",
            "    --angular-momentum-conservation-during-circularisation",
            "    --allow-rlof-at-birth                                           # allow binaries that have one or both stars in RLOF at birth to evolve, particularly useful in the context of CHE binaries",
            "    --circularise-binary-during-mass-transfer",
            "    --hmxr-binaries",
            "    --use-mass-transfer",
            "    --retain-core-mass-during-caseA-mass-transfer",
            "",
            "    ### COMMON ENVELOPE",
            "    --common-envelope-allow-immediate-RLOF-post-CE-survive",
            "    --common-envelope-allow-main-sequence-survive                   # Allow main sequence stars to survive CE",
            "    --common-envelope-allow-radiative-envelope-survive",
            "    --common-envelope-lambda-nanjing-enhanced",
            "    --common-envelope-lambda-nanjing-interpolate-in-mass",
            "    --common-envelope-lambda-nanjing-interpolate-in-metallicity",
            "    --common-envelope-lambda-nanjing-use-rejuvenated-mass",
            "    --revised-energy-formalism-nandez-ivanova",
            "",
            "    ### SUPERNOVAE, KICKS AND REMNANTS",
            "    --allow-non-stripped-ECSN",
            "    --pair-instability-supernovae",
            "    --pulsational-pair-instability",
            "    --USSN-kicks-override-mandel-muller",
            "",
            "    ### PULSAR PARAMETERS",
            "    --evolve-pulsars",
            "",
            "   ### WHITE DWARF PARAMETERS",
            "    --evolve-double-white-dwarfs",
            "",
            "",
            "numericalChoices:",
            "",
            "    ### LOGISTICS",
            "    --debug-level",
            "    --logfile-common-envelopes-record-types",
            "    --logfile-detailed-output-record-types",
            "    --logfile-double-compact-objects-record-types",
            "    --logfile-pulsar-evolution-record-types",
            "    --logfile-rlof-parameters-record-types",
            "    --logfile-supernovae-record-types",
            "    --logfile-system-snapshot-log-record-types",
            "    --logfile-system-parameters-record-types",
            "    --grid-lines-to-process",
            "    --grid-start-line",
            "    --hdf5-chunk-size",
            "    --hdf5-buffer-size",
            "    --log-level",
            "    --mass-change-fraction                                          # approximate desired fractional changes in stellar mass per timestep",
            "    --maximum-evolution-time                                        # maximum physical time a system can be evolved [Myr]",
            "    --maximum-number-timestep-iterations",
            "    --number-of-systems                                             # number of systems per batch",
            "    --radial-change-fraction                                        # approximate desired fractional changes in stellar radius per timestep",
            "    --system-snapshot-age-thresholds                                # age thresholds for the system snapshot log",
            "    --system-snapshot-time-thresholds                               # time thresholds for the system snapshot log",
            "    --timestep-multiplier                                           # optional multiplier relative to default time step duration",
            "    --timestep-multipliers                                          # optional phase-dependent multipliers relative to default time step duration",
            "",
            "    ### STELLAR PROPERTIES",
            "    --cool-wind-mass-loss-multiplier",
            "    --initial-mass                                                  # initial mass for SSE",
            "    --initial-mass-function-min                                     # use 5.0 for DCOs [Msol]",
            "    --initial-mass-function-max                                     # stellar tracks extrapolated above 50 Msol (Hurley+2000) [Msol]",
            "    --initial-mass-function-power",
            "    --luminosity-to-mass-threshold",
            "    --metallicity                                                   # metallicity for both SSE and BSE - Solar metallicity Asplund+2010",
            "    --metallicity-min",
            "    --metallicity-max",
            "    --luminous-blue-variable-multiplier",
            "    --overall-wind-mass-loss-multiplier",
            "    --random-seed",
            "    --rotational-frequency",
            "    --rotational-frequency-1",
            "    --rotational-frequency-2",
            "    --scale-terminal-wind-velocity-with-metallicity-power",
            "    --wolf-rayet-multiplier",
            "",
            "    ### BINARY PROPERTIES",
            "    --eccentricity                                                  # eccentricity for BSE",
            "    --eccentricity-min",
            "    --eccentricity-max",
            "    --initial-mass-1                                                # primary initial mass for BSE",
            "    --initial-mass-2                                                # secondary initial mass for BSE",
            "    --mass-ratio",
            "    --mass-ratio-min",
            "    --mass-ratio-max",
            "    --minimum-sampled-secondary-mass                                # Brown dwarf limit [Msol]",
            "    --orbital-period                                                # orbital period for BSE",
            "    --orbital-period-min                                            # [days]",
            "    --orbital-period-max                                            # [days]",
            "    --semi-major-axis                                               # semi-major axis for BSE",
            "    --semi-major-axis-min                                           # [AU]",
            "    --semi-major-axis-max                                           # [AU]",
            "",
            "    ### MASS TRANSFER",
            "    --convective-envelope-mass-threshold                            # Only if using envelope-state-prescription = 'CONVECTIVE_MASS_FRACTION'",
            "    --convective-envelope-temperature-threshold                     # Only if using envelope-state-prescription = 'FIXED_TEMPERATURE'",
            "    --critical-mass-ratio-HG-degenerate-accretor",
            "    --critical-mass-ratio-HG-non-degenerate-accretor",
            "    --critical-mass-ratio-MS-high-mass-degenerate-accretor",
            "    --critical-mass-ratio-MS-high-mass-non-degenerate-accretor",
            "    --critical-mass-ratio-MS-low-mass-degenerate-accretor",
            "    --critical-mass-ratio-MS-low-mass-non-degenerate-accretor",
            "    --critical-mass-ratio-giant-degenerate-accretor",
            "    --critical-mass-ratio-giant-non-degenerate-accretor",
            "    --critical-mass-ratio-helium-HG-degenerate-accretor",
            "    --critical-mass-ratio-helium-HG-non-degenerate-accretor",
            "    --critical-mass-ratio-helium-MS-degenerate-accretor",
            "    --critical-mass-ratio-helium-giant-degenerate-accretor",
            "    --critical-mass-ratio-helium-MS-non-degenerate-accretor",
            "    --critical-mass-ratio-helium-giant-non-degenerate-accretor",
            "    --critical-mass-ratio-white-dwarf-degenerate-accretor",
            "    --critical-mass-ratio-white-dwarf-non-degenerate-accretor",
            "    --mass-transfer-fa                                              # Only if using mass-transfer-accretion-efficiency-prescription = 'FIXED'",
            "    --mass-transfer-jloss                                           # Only if using mass-transfer-angular-momentum-loss-prescription = 'FIXED'",
            "    --mass-transfer-jloss-linear-fraction-degen",
            "    --mass-transfer-jloss-linear-fraction-non-degen",
            "    --mass-transfer-thermal-limit-C",
            "    --zeta-adiabatic-arbitrary",
            "    --zeta-main-sequence",
            "    --zeta-radiative-envelope-giant",
            "",
            "    ### COMMON ENVELOPE",
            "    --common-envelope-alpha",
            "    --common-envelope-alpha-thermal                                 # lambda = alpha_th*lambda_b + (1-alpha_th)*lambda_g",
            "    --common-envelope-lambda                                        # Only if using 'LAMBDA_FIXED'",
            "    --common-envelope-lambda-multiplier                             # Multiply common envelope lambda by some constant",
            "    --common-envelope-mass-accretion-constant",
            "    --common-envelope-mass-accretion-max                            # For 'MACLEOD+2014' [Msol]",
            "    --common-envelope-mass-accretion-min                            # For 'MACLEOD+2014' [Msol]",
            "    --common-envelope-recombination-energy-density",
            "    --common-envelope-second-stage-beta",
            "    --common-envelope-slope-kruckow",
            "    --maximum-mass-donor-nandez-ivanova",
            "",
            "    ### SUPERNOVAE, KICKS AND REMNANTS",
            "    --eddington-accretion-factor                                    # multiplication Factor for eddington accretion onto NS&BH",
            "    --fix-dimensionless-kick-magnitude",
            "    --fryer-22-fmix                                                 # parameter describing mixing growth time when using the 'FRYER2022' remnant mass prescription",
            "    --fryer-22-mcrit                                                # critical mass for BH formation when using the 'FRYER2022' remnant mass prescription",
            "    --kick-direction-power",
            "    --kick-magnitude-sigma-CCSN-NS                                  # [km/s]",
            "    --kick-magnitude-sigma-CCSN-BH                                  # [km/s]",
            "    --kick-magnitude-max",
            "    --kick-magnitude-random                                         # (SSE) used to draw the kick magnitude for the star should it undergo a supernova event",
            "    --kick-magnitude                                                # (SSE) (drawn) kick magnitude for the star should it undergo a supernova event [km/s]",
            "    --kick-magnitude-random-1                                       # (BSE) used to draw the kick magnitude for the primary star should it undergo a supernova event",
            "    --kick-magnitude-1                                              # (BSE) (drawn) kick magnitude for the primary star should it undergo a supernova event [km/s]",
            "    --kick-theta-1                                                  # (BSE) angle between the orbital plane and the 'z' axis of the supernova vector for the primary star should it undergo a supernova event [radians]",
            "    --kick-phi-1                                                    # (BSE) angle between 'x' and 'y', both in the orbital plane of the supernova vector, for the primary star should it undergo a supernova event [radians]",
            "    --kick-mean-anomaly-1                                           # (BSE) mean anomaly at the instant of the supernova for the primary star should it undergo a supernova event - should be uniform in [0, 2pi) [radians]",
            "    --kick-magnitude-random-2                                       # (BSE) used to draw the kick velocity for the secondary star should it undergo a supernova event",
            "    --kick-magnitude-2                                              # (BSE) (drawn) kick magnitude for the secondary star should it undergo a supernova event [km/s]",
            "    --kick-theta-2                                                  # (BSE) angle between the orbital plane and the 'z' axis of the supernova vector for the secondary star should it undergo a supernova event [radians]",
            "    --kick-phi-2                                                    # (BSE) angle between 'x' and 'y', both in the orbital plane of the supernova vector, for the secondary star should it undergo a supernova event [radians]",
            "    --kick-mean-anomaly-2                                           # (BSE) mean anomaly at the instant of the supernova for the secondary star should it undergo a supernova event - should be uniform in [0, 2pi) [radians]",
            "    --kick-magnitude-sigma-ECSN                                     # [km/s]",
            "    --kick-magnitude-sigma-USSN                                     # [km/s]",
            "    --kick-scaling-factor",
            "    --maximum-neutron-star-mass",
            "    --mcbur1",
            "    --muller-mandel-kick-multiplier-BH                              # scaling prefactor for BH kicks when using the 'MULLERMANDEL' kick magnitude distribution",
            "    --muller-mandel-kick-multiplier-NS                              # scaling prefactor for NS kicks when using the 'MULLERMANDEL' kick magnitude distribution",
            "    --muller-mandel-sigma-kick-BH                                   # BH kick scatter when using the 'MULLERMANDEL' kick magnitude distribution",
            "    --muller-mandel-sigma-kick-NS                                   # NS kick scatter when using the 'MULLERMANDEL' kick magnitude distribution",
            "    --neutrino-mass-loss-BH-formation-value",
            "    --pisn-lower-limit                                              # Minimum core mass for PISN [Msol]",
            "    --pisn-upper-limit                                              # Maximum core mass for PISN [Msol]",
            "    --ppi-lower-limit                                               # Minimum core mass for PPI [Msol]",
            "    --ppi-upper-limit                                               # Maximum core mass for PPI [Msol]",
            "    --ppi-co-core-shift-hendriks                                    # CO Core shift for PPI [Msol] from Hendriks+23",
            "    --rocket-kick-magnitude-1                                       # (BSE) rocket kick magnitude for the primary should it undergo a supernova event [km/s]",
            "    --rocket-kick-magnitude-2                                       # (BSE) rocket kick magnitude for the secondary should it undergo a supernova event [km/s]",
            "    --rocket-kick-theta-1                                           # (BSE) angle between the orbital plane and the 'z' axis of the rocket kick for the primary star [radians]",
            "    --rocket-kick-phi-1                                             # (BSE) angle between 'x' and 'y', both in the orbital plane of the rocket kick , for the primary star [radians]",
            "    --rocket-kick-theta-2                                           # (BSE) angle between the orbital plane and the 'z' axis of the rocket kick for the secondary star [radians]",
            "    --rocket-kick-phi-2                                             # (BSE) angle between 'x' and 'y', both in the orbital plane of the rocket kick , for the secondary star [radians]",
            "",
            "    ### PULSAR PARAMETERS",
            "    --pulsar-birth-magnetic-field-distribution-min                  # [log10(B/G)]",
            "    --pulsar-birth-magnetic-field-distribution-max                  # [log10(B/G)]",
            "    --pulsar-birth-magnetic-field-distribution-mean                 # [log10(B/G)]",
            "    --pulsar-birth-magnetic-field-distribution-sigma                # [log10(B/G)]",
            "    --pulsar-birth-spin-period-distribution-min                     # [ms]",
            "    --pulsar-birth-spin-period-distribution-max                     # [ms]",
            "    --pulsar-birth-spin-period-distribution-mean                    # [ms]",
            "    --pulsar-birth-spin-period-distribution-sigma                   # [ms]",
            "    --pulsar-magnetic-field-decay-timescale                         # [Myr]",
            "    --pulsar-magnetic-field-decay-massscale                         # [Msol]",
            "    --pulsar-minimum-magnetic-field                                 # [log10(B/G)]",
            "",
            "",
            "stringChoices:",
            "",
            "    ### LOGISTICS",
            "    --add-options-to-sysparms",
            "    --fp-error-mode                                                 # specifies floating-point error handling mode",
            "    --grid                                                          # grid file name (e.g. 'mygrid.txt')",
            "    --mode                                                          # evolving single (SSE) or binary stars (BSE)",
            "    --notes",
            "    --notes-hdrs",
            "    --output-container",
            "    --timesteps-filename",
            "",
            "    ### STELLAR PROPERTIES",
            "    --chemically-homogeneous-evolution-mode                         # chemically homogeneous evolution mode",
            "    --envelope-state-prescription",
            "    --initial-mass-function",
            "    --LBV-mass-loss-prescription",
            "    --main-sequence-core-mass-prescription",
            "    --mass-loss-prescription",
            "    --OB-mass-loss-prescription",
            "    --RSG-mass-loss-prescription",
            "    --VMS-mass-loss-prescription",
            "    --WR-mass-loss-prescription",
            "    --metallicity-distribution",
            "    --pulsational-pair-instability-prescription",
            "",
            "    ### BINARY PROPERTIES",
            "    --eccentricity-distribution",
            "    --mass-ratio-distribution",
            "    --orbital-period-distribution",
            "    --rotational-velocity-distribution",
            "    --semi-major-axis-distribution",
            "",
            "    ### MASS TRANSFER",
            "    --case-BB-stability-prescription",
            "    --critical-mass-ratio-prescription",
            "    --stellar-zeta-prescription",
            "    --mass-transfer-angular-momentum-loss-prescription",
            "    --mass-transfer-accretion-efficiency-prescription",
            "    --mass-transfer-rejuvenation-prescription",
            "    --mass-transfer-thermal-limit-accretor-multiplier",
            "    --response-to-spin-up",
            "",
            "    ### COMMON ENVELOPE",
            "    --common-envelope-formalism",
            "    --common-envelope-lambda-prescription                           # Xu & Li 2010",
            "    --common-envelope-mass-accretion-prescription",
            "    --common-envelope-second-stage-gamma-prescription",
            "",
            "    ### TIDES",
            "    --tides-prescription",
            "",
            "    ### SUPERNOVAE, KICKS AND REMNANTS",
            "    --black-hole-kicks-mode",
            "    --fryer-supernova-engine",
            "    --kick-magnitude-distribution",
            "    --kick-direction-distribution",
            "    --maltsev-fallback",
            "    --maltsev-mode",
            "    --neutron-star-accretion-in-ce",
            "    --neutron-star-equation-of-state",
            "    --neutrino-mass-loss-BH-formation",
            "    --pulsar-birth-magnetic-field-distribution",
            "    --pulsar-birth-spin-period-distribution",
            "    --remnant-mass-prescription",
            "",
            "    ### LOGFILES AND OUTPUTS ",
            "    --logfile-type",
            "    --logfile-name-prefix",
            "    --logfile-definitions",
            "    --logfile-common-envelopes",
            "    --logfile-detailed-output",
            "    --logfile-double-compact-objects",
            "    --logfile-pulsar-evolution",
            "    --logfile-rlof-parameters",
            "    --logfile-supernovae",
            "    --logfile-switch-log",
            "    --logfile-system-snapshot-log",
            "    --logfile-system-parameters",
            "    --output-path",
            "",
            "",
            "listChoices: ",
            "",
            "    --log-classes",
            "    --debug-classes",
    };

}
