#pragma once

#define ZDEP ZDependent::Instance()

#include <optional>
#include <vector>
#include <tuple>

#include "constants.h"
#include "typedefs.h"
#include "typealiases.h"


////////////////////////////////////////////////////////////////////////////////////////
//                                                                                    //
//                       Metallicity Dependent Singleton Object                       //
//                                                                                    //
// Singletons and global variables are sometimes frowned-upon, but doing it this way  //
// means the objects don't need to be passed around to all and sundry.  Convenience   //
// and clarity sometimes trump dogma.                                                 //
////////////////////////////////////////////////////////////////////////////////////////


// We implement a small cache for metallicity-dependent values.
//
// While the metallicity of a star can change throughout the lifetime of the star, in
// a typical COMPAS run it does not.  Even so, if the metallicity of a star is allowed
// to change over its lifetime, it is unlikely to change at every timestep.  Moreover,
// while the stars in a population generated by a COMPAS run can have their initial
// metallicities sampled from a uniform distribution, in a typical COMPAS run the
// initial metallicities are either the same for each star, or taken from a small grid
// of metallicities.
//
// In the scenarios described above there is some (varying) benefit in caching values
// already calculated in an effort to save compute cycles - even in the case of the
// initial metallicities sampled from a uniform distribution (though probably small in
// that case).
// 
// Cache properties:
//
//   - configurable size (--metallicity-cache-size, 1..64, default 16)
//   - keyed by absolute Z value with tolerance Z_CACHE_TOL = 1e-7
//   - FIFO eviction when the cache is full and a new Z value arrives
//
// Defaults assume the typical COMPAS pattern (small discrete Z set, high intra-binary
// locality) - larger caches are an option for users who need them.
//
// Cache operations:
//
// The cache is initialised on class construction.
// Callers pass a metallicity to the getters.  On a cache hit (an entry exists within
// Z_CACHE_TOL of the requested metallicity) the cached values are returned. On a miss,
// the values are calculated for requested metallicity, inserted into the cache (using
// FIFO eviction if the cache is full), and returned.
//
// The cache members are 'mutable' so the access methods can be 'const' - from the
// caller's perspective, asking for the values at a given Z is a pure operation - same
// metallicity in, same values out.
//
// 

struct ZSlotDetailsT {  // Z-cache slot details
    SizeT  slot;        // Cache slot (m_Keys[slot], m_Cache[slot])
    double Z;           // Metallicity at slot
};


class ZDependent {

    // Structs that define the cache are shown below.

    // HurleyZDependentT
    //
    // The Z-dependent values from Hurley et al. 2000.
    // 
    // The 'a' and 'b' coefficients depend only on Z (via sigma and zeta).  The constants
    // derived from them (alpha, gamma, luminosity constants, radius constants, mass cutoffs)
    // are therefore also Z-dependent.
    //
    // All values are guaranteed to be populated if the HurleyZDependent struct contains a value
    // (per .has_value()).  See ZDependentT struct below.
    struct HurleyZDependentT {
        double     rho;                 // Rho - Hurley et al. 2000 eq 2
        double     gbRadiusXExponent;   // GB radius x exponent - Hurley et al. 2000
        double     lMinCHeB;            // Minimum luminosity on the CHeB phase

        // The following variables are each constructed as a std::array (much better for
        // optimising than std::vector, especially when being passed as parameters). 
        //
        // A small wrinkle is that the size of a std::array must be fixed, and known at
        // compile time.  Fortunately, the size of each of these arrays is fixed by Hurley
        // (see Hurley et al., 2000)

        HurleyACoeffsT     aCoeffs;     // a coefficients - Hurley et al. 2000 appendix A
        HurleyBCoeffsT     bCoeffs;     // b coefficients - Hurley et al. 2000 appendix B
        HurleyAlphasT      alphas;      // Alphas - derived from b coefficients - Hurley et al. 2000
        HurleyGConstsT     gammas;      // Gammas - derived from a coefficients - Hurley et al. 2000
        HurleyLConstsT     LConstants;  // Luminosity constants - derived from a coefficients - Hurley et al. 2000
        HurleyRConstsT     RConstants;  // Radius constants - derived from a coefficients - Hurley et al. 2000
        HurleyMassCutoffsT massCutoffs; // Mass cutoffs - Hurley et al. 2000
    };


    // ShikauchiZDependentT
    //
    // The Z-dependent values from Shikauchi et al. 2024.
    //
    // All values are guaranteed to be populated if the ShikauchiZDependentT struct contains a value
    // (per .has_value()).  See ZDependentT struct below.
    struct ShikauchiZDependentT {
        ShikauchiACoeffsT alphaCoeffs;      // alpha: the natural decline rate of fMix
        ShikauchiFCoeffsT fMixCoeffs;       // fMix: fraction of mass in mixing core at ZAMS
        ShikauchiLCoeffsT luminosityCoeffs; // Luminosity
    };


    // ZDependentT
    //
    // A single metallicity-keyed cache entry. Every value here is derivable from the metallicity
    // (and from various constants in constants.h).
    // 
    // These are (re)calculated when the Z value passed to ZDependent::Values() is one that does not
    // have a cached entry within tolerance (see Z_CACHE_TOL in constants.h) - with the exception
    // of the optional values (wrapped in std::optional<>), which are (re)calculated on demand.
    struct ZDependentT {

        // Let 'Z' be the metallicity value pertaining to cache entry represented by this struct...

        // Scalar Z-derived values
        double zetaHurley;              // log10(Z / ZSOL_HURLEY) (used often, so here rather than in HurleyZDependentT)
        double zScaledHurley;           // Z / ZSOL_HURLEY (used often, so here rather than in HurleyZDependentT)
        double log10Z;                  // log10(Z)  (what Hurley calls "sigma" - alias SigmaHurley())
        double zetaAnders;              // log10(Z / ZSOL_ANDERS)
        double zetaAsplund;             // log10(Z / ZSOL_ASPLUND)
        double zScaledAnders;           // Z / ZSOL_ANDERS
        double zScaledAsplund;          // Z / ZSOL_ASPLUND

        // ZAMS H and He abundances (Pols 1998).
        // To be clear about what these values are: they are the ZAMS abundances the star would
        // have if its ZAMS metallicity was Z.
        double HAbundanceAtZAMS;        // ZAMS hydrogen abundance
        double HeAbundanceAtZAMS;       // ZAMS helium abundance

        // Tout 1996 ZAMS luminosity and radius coefficient arrays.
        // To be clear about what these values are: they are the ZAMS luminosity and radius
        // coefficients per Tout et al. 1996, for a ZAMS metallicity of Z.
        ToutLCoeffsT ToutZAMSLCoeffs;
        ToutRCoeffsT ToutZAMSRCoeffs;

        // The following optional structs are populated only when required.
        //
        // The Hurley 2000 Z-dependent values are only required if one of the Hurley
        // evolution modes is specified via the program options.
        // Shikauchi 2024 Z-dependent values are only required if the BRCEK MS core mass
        // prescription is specified via the program options, and the star starts on MS
        // (the dependency is enforced by the options code).
        //
        // We don't check the program option values here - that would be too much overhead
        // for each call to the ZDependent code - what we do instead is wrap these structs
        // in std::optional<>, and then calculate the values contained within the structs
        // the first time they are requested.
        //
        // We use the ".has_value()" function for std::optional, which is about as free
        // (wrt performance) as we can get - at most ~1 clock cycle, and very often actually
        // free, so we can do (a conservative) ~2-4 billion checks, depending on the CPU
        // being used, and still only add 1 second to the run time).
        //
        // The assumption is that the code will only request these values if the associated
        // program options have been specified (if that's not true there's a problem somewhere
        // in the code...).  Once calculated (at first on-demand request) they don't need to
        // be calculated again (for that Z).
        std::optional<HurleyZDependentT>    Hurley;
        std::optional<ShikauchiZDependentT> Shikauchi;
    };

public:

    ~ZDependent() {
        m_Instantiated = false;
    }

    static ZDependent* Instance() {
        static ZDependent self;
        m_Instantiated = true;          // Set after `self` is fully constructed
        return &self;
    }

    static bool IsInstantiated() { return m_Instantiated; }

    void Resize(const SizeT p_CacheSize);
   

    /* 
     * ZAtSlot
     *
     * @brief
     * Returns cache slot details (slot number and metallicity) for specified metallicity.
     * If no cache slot holds the specified metallicity, returns std::nullopt.
     * 
     * 
     * OptDblT ZAtSlot(const SizeT p_Slot) const
     * 
     * @param       p_Slot                          Cache slot number
     * @return                                      OptDblT metallicity value associated with the cache slot.
     *                                              Will be std::nullopt if the cache slot does not exist.
     */ 
    [[gnu::always_inline]] OptDblT ZAtSlot(const SizeT p_Slot) const { 
        return (p_Slot < m_CacheCount) ? std::optional<double>(m_Keys[p_Slot]) : std::nullopt;
    }
    

    /* 
     * SlotAtZ
     *
     * @brief
     * Returns cache slot details (slot number and metallicity) for specified metallicity.
     * If no cache slot holds the specified metallicity, returns std::nullopt.
     * 
     * 
     * std::optional<ZSlotDetailsT> SlotAtZ(const double p_Z) const
     * 
     * @param       p_Z                             The metallicity to find in the cache
     * @return                                      std::optional<ZSlotDetailsT> that contains:
     *                                                 - the cache slot index (type SizeT)
     *                                                 - the metallicity value associated with the cache slot
     *                                              Will be std::nullopt if metallicity not found in cache.
     */ 
    [[gnu::always_inline]] std::optional<ZSlotDetailsT> SlotAtZ(const double p_Z) const {
        std::optional<SizeT> slot = FindSlot(p_Z);
        if (slot.has_value()) return ZSlotDetailsT{*slot, m_Keys[*slot]};
        return std::nullopt;
    }


    // Getters
    //
    // The Values() function is not exposed publicly.  Consumers of the ZDependent singleton
    // are provided with getters that return specific values from the cache.  All getters take
    // metallicity as a parameter - this is the key into the cache, and the metallicity used
    // to calculate the values returned.
    //
    // Getters for cached values that are simple values take metallicity as the only parameter.
    // Getters for cached values that are arrays come in two forms:
    //
    //    - One form takes two parameters - metallicity and an index - and returns the value of
    //      the array element at that index for the specified metallicity.  For this form of
    //      the getter, the index is checked against the bounds of the array, and if it is out
    //      of bounds the getter fails and the program is terminated with ERROR::OUT_OF_BOUNDS.
    //
    //    - The other form takes one parameter only - metallicity - and returns a const reference
    //      to the array in the cache (of type appropriate for the getter called).  This is a
    //      pointer into the cache - so that there is no copying of the array (so saving compute
    //      cycles).  Since it is a const reference, the caller can read the values in the cache
    //      but cannot change them.
    //
    //      There is an *important caveat* for this form of the getter: the reference to the array
    //      that is returned could become stale.  The reference is valid only while the ZDependent
    //      object is alive, and the cache slot hasn't been evicted or overwritten.  The reference
    //      returned is essentially a pointer to an area of memory occupied by the cache slot, and
    //      the best usage pattern for it is "get the reference, read the values required, use the
    //      values, then forget the reference".  The reason is that the cache is mutable, so even
    //      a const lookup can mutate it — a miss fills a slot, and once the cache is full, a miss
    //      needs to evict a cache slot so that a new set of values can be cached.  So if a caller
    //      stashes the reference and then makes another ZDEP call with a different metallicity that
    //      triggers a miss, the slot behind the reference could be reused for the new metallicity,
    //      and the stashed reference now reads the wrong data (or, if the cache has been downsized
    //      it will be pointing at values unrelated to the Z-cache).
    //
    //      Given the paragraph above, the best thing to do is not stash a reference to a cached
    //      array and reuse it.  However, if for some (currently) unforeseen reason it is considered
    //      necessary to stash and reuse a reference to a cached array, code should check whether
    //      the reference has become stale before it is reused.  Tools to facilitate that check are
    //      provided:
    //
    //
    //      std::optional<ZSlotDetailsT> SlotAtZ(const double p_Z)
    //
    //      This function takes metallicity as a parameter and returns the cache slot details (type
    //      ZSlotDetailsT) if the metallicity value is found in the cache (tolerance Z_CACHE_TOL).
    //      The return value is wrapped in std::optional<>, and if the metallicity is not found in
    //      the cache std::nullopt is returned (no value).
    //
    //
    //      OptDblT ZAtSlot(const SizeT p_Slot)
    //
    //      This function takes a cache slot number as a parameter and returns the metallicity
    //      stored at that cache slot if the slot exists in the cache.  The return value is wrapped
    //      in std::optional<>, and if the metallicity is not found in the cache std::nullopt is
    //      returned (no value).
    //
    //
    //      Z-cache users can use some combination of the above two functions to check whether any
    //      stashed reference to a cache entry is still valid:
    //
    //      If the optional value returned by either of the functions (which one will depend on how
    //      they are used) does not have an assigned value, the stashed reference should not be used.
    //      In this case the (previously retrieved) cache entry no longer exists, and the stashed
    //      reference will be pointing at a memory location unrelated to the Z-cache.
    //
    //      If the optional value returned does have an assigned value, for ZAtSlot() it is the
    //      metallicity used to calculate the values in that cache slot, and for SlotAtZ() it is
    //      the slot details for the specified metallicity - including the slot number and actual
    //      metallicity used to calculate the values in that cache slot.  If the metallicity used to
    //      calculate the values in the cache slot is not the same (within Z_CACHE_TOL) as the
    //      metallicity associated with the stashed reference, the stashed reference should not be
    //      used (it is a stale pointer).  A stale reference should never be used - a new reference
    //      should be obtained by calling the appropriate getter again.
    //
    //      Note also for this form of the getter, the caller is responsible for bounds checking access
    //      to array elements.
    //
    //      A final note on use of this form of getter.  As described above, the getter returns a 
    //      const reference to an array, and that is so that no copy of the array is performed (to
    //      reduce compute cycles) - the array can be accessed in situ.  But that doesn't force the
    //      caller to accept a reference - the caller could, for example, call a getter as follows:
    //
    //          HurleyACoeffsT aCoeffs = ZDEP->HurleyACoeffs(0.017);
    //
    //      and in this case aCoeffs is an array copied from the values in the cache slot. 
    //
    //
    //      Design note:
    //
    //      I did consider writing getters of this form so that they would always return a tuple that
    //      would include a ZSlotDetailsT struct and the reference to the array.  In the end I decided
    //      that the overhead of doing that for every call to the getters wasn't warranted.  The cache
    //      slot details are only required in the event that a developer decides to stash an array
    //      reference - that's not the recommended best-practice path, so if a developer decides to do
    //      that, the onus is on them to check for a stale reference, and to incur the performance
    //      penalty.  Developers that follow best-practices shouldn't be penalised on the off-chance
    //      that someone else may not follow that path.


    // Values that are always present (i.e. not wrapped in std::optional<>)

    double ZetaHurley(const double p_Z) const        { return Values(p_Z).zetaHurley; }
    double ZScaledHurley(const double p_Z) const     { return Values(p_Z).zScaledHurley; }
    double Log10Z(const double p_Z) const            { return Values(p_Z).log10Z; }
    double SigmaHurley(const double p_Z) const       { return Log10Z(p_Z); }
    double ZetaAnders(const double p_Z) const        { return Values(p_Z).zetaAnders; }
    double ZetaAsplund(const double p_Z) const       { return Values(p_Z).zetaAsplund; }
    double ZScaledAnders(const double p_Z) const     { return Values(p_Z).zScaledAnders; }
    double ZScaledAsplund(const double p_Z) const    { return Values(p_Z).zScaledAsplund; }

    double HAbundanceAtZAMS(const double p_Z) const  { return Values(p_Z).HAbundanceAtZAMS; }
    double HeAbundanceAtZAMS(const double p_Z) const { return Values(p_Z).HeAbundanceAtZAMS; }

    const ToutLCoeffsT& ToutLuminosityCoeffs(const double p_Z) const { return Values(p_Z).ToutZAMSLCoeffs; }
    double ToutLuminosityCoeffs(const double p_Z, const SizeT p_Idx) const {
        const auto& v = Values(p_Z);
        if (p_Idx < v.ToutZAMSLCoeffs.size()) return v.ToutZAMSLCoeffs[p_Idx];
        utils::Fail(ERROR::OUT_OF_BOUNDS);
    }

    const ToutRCoeffsT& ToutRadiusCoeffs(const double p_Z) const { return Values(p_Z).ToutZAMSRCoeffs; }
    double ToutRadiusCoeffs(const double p_Z, const SizeT p_Idx) const { 
        const auto& v = Values(p_Z);
        if (p_Idx < v.ToutZAMSRCoeffs.size()) return v.ToutZAMSRCoeffs[p_Idx];
        utils::Fail(ERROR::OUT_OF_BOUNDS);
    }


    // Optional values (i.e. wrapped in std::optional<>)
    //
    // For these getters we check if the optional value has been set by calling .has_value()
    // via the inline function EnsureHurley().

    // Hurley Z-dependent values

    double HurleyRho(const double p_Z) const                 { return EnsureHurley(p_Z).Hurley->rho; }
    double HurleyGBRadiusXExponent(const double p_Z) const   { return EnsureHurley(p_Z).Hurley->gbRadiusXExponent; }
    double HurleyMinLuminosityOnCHeB(const double p_Z) const { return EnsureHurley(p_Z).Hurley->lMinCHeB; }

    // a coefficients array.
    // We expose the array, and provide an indexed getter.
    const HurleyACoeffsT& HurleyACoeffs(const double p_Z) const {return EnsureHurley(p_Z).Hurley->aCoeffs; }
    double HurleyACoeffs(const double p_Z, const SizeT p_Idx) const { 
        const auto& v = EnsureHurley(p_Z);
        if (p_Idx < v.Hurley->aCoeffs.size()) return v.Hurley->aCoeffs[p_Idx];
        utils::Fail(ERROR::OUT_OF_BOUNDS);
    }

    // b coefficients array.
    // We expose the array, and provide an indexed getter.
    const HurleyBCoeffsT& HurleyBCoeffs(const double p_Z) const {return EnsureHurley(p_Z).Hurley->bCoeffs; }
    double HurleyBCoeffs(const double p_Z, const SizeT p_Idx) const {
        const auto& v = EnsureHurley(p_Z);
        if (p_Idx < v.Hurley->bCoeffs.size()) return v.Hurley->bCoeffs[p_Idx];
        utils::Fail(ERROR::OUT_OF_BOUNDS);
    }

    // Alpha constants scalars.
    // We expose the array, and provide an indexed getter.
    // We also provide individual getters for each value.
    //
    // Note that the array has 3 values that correspond to Hurley's alpha1, alpha3,
    // and alpha4 (alpha2 is not Z-dependent and is calculated elsewhere).
    const HurleyAlphasT& HurleyAlphas(const double p_Z) const { return EnsureHurley(p_Z).Hurley->alphas; }
    double HurleyAlphas(const double p_Z, const SizeT p_Idx) const {
        const auto& v = EnsureHurley(p_Z);
        if (p_Idx < v.Hurley->alphas.size()) return v.Hurley->alphas[p_Idx];
        utils::Fail(ERROR::OUT_OF_BOUNDS);
    }
    double HurleyAlpha1(const double p_Z) const { return EnsureHurley(p_Z).Hurley->alphas[0]; }
    double HurleyAlpha3(const double p_Z) const { return EnsureHurley(p_Z).Hurley->alphas[1]; }
    double HurleyAlpha4(const double p_Z) const { return EnsureHurley(p_Z).Hurley->alphas[2]; }

    // Gamma constants scalars.
    // We expose the array, and provide an indexed getter.
    // We also provide individual getters for each value.
    const HurleyGConstsT& HurleyGConsts(const double p_Z) const { return EnsureHurley(p_Z).Hurley->gammas; }
    double HurleyGConsts(const double p_Z, const SizeT p_Idx) const {
        const auto& v = EnsureHurley(p_Z);
        if (p_Idx < v.Hurley->gammas.size()) return v.Hurley->gammas[p_Idx];
        utils::Fail(ERROR::OUT_OF_BOUNDS);
    }
    double HurleyBGamma(const double p_Z) const { return EnsureHurley(p_Z).Hurley->gammas[0]; }
    double HurleyCGamma(const double p_Z) const { return EnsureHurley(p_Z).Hurley->gammas[1]; }
   
    // Luminosity constants scalars.
    // We expose the array, and provide an indexed getter.
    // We also provide individual getters for each value.
    const HurleyLConstsT& HurleyLConsts(const double p_Z) const { return EnsureHurley(p_Z).Hurley->LConstants; }
    double HurleyLConsts(const double p_Z, const SizeT p_Idx) const {
        const auto& v = EnsureHurley(p_Z);
        if (p_Idx < v.Hurley->LConstants.size()) return v.Hurley->LConstants[p_Idx];
        utils::Fail(ERROR::OUT_OF_BOUNDS);
    }
    double HurleyBAlphaL(const double p_Z) const { return EnsureHurley(p_Z).Hurley->LConstants[0]; }
    double HurleyBBetaL(const double p_Z) const  { return EnsureHurley(p_Z).Hurley->LConstants[1]; }
    double HurleyBDeltaL(const double p_Z) const { return EnsureHurley(p_Z).Hurley->LConstants[2]; }
   
    // Radius constants scalars.
    // We expose the array, and provide an indexed getter.
    // We also provide individual getters for each value.
    const HurleyRConstsT& HurleyRConsts(const double p_Z) const { return EnsureHurley(p_Z).Hurley->RConstants; }
    double HurleyRConsts(const double p_Z, const SizeT p_Idx) const {
        const auto& v = EnsureHurley(p_Z);
        if (p_Idx < v.Hurley->RConstants.size()) return v.Hurley->RConstants[p_Idx];
        utils::Fail(ERROR::OUT_OF_BOUNDS);
    }
    double HurleyBAlphaR(const double p_Z) const { return EnsureHurley(p_Z).Hurley->RConstants[0]; }
    double HurleyCAlphaR(const double p_Z) const { return EnsureHurley(p_Z).Hurley->RConstants[1]; }
    double HurleyBBetaR(const double p_Z) const  { return EnsureHurley(p_Z).Hurley->RConstants[2]; }
    double HurleyCBetaR(const double p_Z) const  { return EnsureHurley(p_Z).Hurley->RConstants[3]; }
    double HurleyBDeltaR(const double p_Z) const { return EnsureHurley(p_Z).Hurley->RConstants[4]; }

    // Mass cutoffs scalars.
    // We expose the array, and provide an indexed getter.
    // We also provide individual getters for each value.
    const HurleyMassCutoffsT& HurleyMassCutoffs(const double p_Z) const { return EnsureHurley(p_Z).Hurley->massCutoffs; }
    double HurleyMassCutoffs(const double p_Z, const SizeT p_Idx) const {
        const auto& v = EnsureHurley(p_Z);
        if (p_Idx < v.Hurley->massCutoffs.size()) return v.Hurley->massCutoffs[p_Idx];
        utils::Fail(ERROR::OUT_OF_BOUNDS);
    }
    double HurleyMCOHook(const double p_Z) const { return EnsureHurley(p_Z).Hurley->massCutoffs[0]; }
    double HurleyMCOHeF(const double p_Z) const  { return EnsureHurley(p_Z).Hurley->massCutoffs[1]; }
    double HurleyMCOFGB(const double p_Z) const  { return EnsureHurley(p_Z).Hurley->massCutoffs[2]; }


    // Shikauchi Z-dependent values

    // Alpha coefficients array.
    // We expose the alphaCoeffs array, and provide an indexed getter.
    const ShikauchiACoeffsT& ShikauchiAlphaCoeffs(const double p_Z) const { return EnsureShikauchi(p_Z).Shikauchi->alphaCoeffs; }
    double ShikauchiAlphaCoeffs(const double p_Z, const SizeT p_Idx) const { 
        const auto& v = EnsureShikauchi(p_Z);
        if (p_Idx < v.Shikauchi->alphaCoeffs.size()) return v.Shikauchi->alphaCoeffs[p_Idx];
        utils::Fail(ERROR::OUT_OF_BOUNDS);
    }

    // fMix coefficients array.
    // We expose the fMixCoeffs array, and provide an indexed getter.
    const ShikauchiFCoeffsT& ShikauchifMixCoeffs(const double p_Z) const { return EnsureShikauchi(p_Z).Shikauchi->fMixCoeffs; }
    double ShikauchifMixCoeffs(const double p_Z, const SizeT p_Idx) const { 
        const auto& v = EnsureShikauchi(p_Z);
        if (p_Idx < v.Shikauchi->fMixCoeffs.size()) return v.Shikauchi->fMixCoeffs[p_Idx];
        utils::Fail(ERROR::OUT_OF_BOUNDS);
    }

    // Luminosity coefficients array.
    // We expose the luminosityCoeffs array, and provide an indexed getter.
    const ShikauchiLCoeffsT& ShikauchiLuminosityCoeffs(const double p_Z) const { return EnsureShikauchi(p_Z).Shikauchi->luminosityCoeffs; }
    double ShikauchiLuminosityCoeffs(const double p_Z, const SizeT p_Idx) const { 
        const auto& v = EnsureShikauchi(p_Z);
        if (p_Idx < v.Shikauchi->luminosityCoeffs.size()) return v.Shikauchi->luminosityCoeffs[p_Idx];
        utils::Fail(ERROR::OUT_OF_BOUNDS);
    }


private:

    ZDependent() { 
        Resize(DEFAULT_Z_CACHE_SIZE);                       // Initialise the cache to default size
    }
    ZDependent(ZDependent const&)              = delete;    // Copy constructor does nothing, and not exposed publicly
    ZDependent& operator = (ZDependent const&) = delete;    // Operator = does nothing, and not exposed publicly

    inline static bool m_Instantiated = false;              // Instantiated flag

    SizeT m_CacheCapacity = 0;                              // Cache capacity - maximum entries. See Resize().


    // The cache uses parallel vectors, indexed in lockstep: m_Cache and m_Keys.
    //
    //     m_Cache is a vector of (struct) ZDependentT, and holds the Z-dependent values.
    //     m_Keys  is a vector of double, and holds the metallicity values for which the
    //             m_Cache values were calculated: m_Keys[i] is the metallicity for m_Cache[i].
    //
    // Separate vector for keys and cached values allows us to just scan through a vector of
    // double when looking for a metallicity in the cache.
   
    mutable DblVectorT               m_Keys;                // Vector of keys
    mutable std::vector<ZDependentT> m_Cache;               // Vector of (struct) ZDependentT - the cached values

    mutable SizeT                    m_CacheCount = 0;      // Number of populated entries (<= m_CacheCapacity)
    mutable SizeT                    m_NextEvict  = 0;      // FIFO eviction pointer (next element to be evicted)
    mutable SizeT                    m_LastFound  = 0;      // Last element viewed or inserted

    // Internal calculation helpers.
    //
    // These are private because the cache is the public interface.  Cache users should not
    // be calculating Z-dependent values directly - the cache operations take care of that.
  

    /* 
     * FindSlot
     *
     * @brief
     * Returns cache slot number for specified metallicity.
     * If no cache slot holds the specified metallicity, returns std::nullopt.
     * 
     * std::optional<SizeT> FindSlot(double p_Z) const
     * 
     * @param       p_Z                             The metallicity to find in the cache
     * @return                                      std::optional<SizeT> slot number.
     *                                              Will be std::nullopt if metallicity not found in cache.
     */ 
    [[gnu::always_inline]] std::optional<SizeT> FindSlot(double p_Z) const {
        // We perform a circular scan of the keys vector to find the required metallicity.  We do
        // this in two parts - saves CPU cycles.  The first part of the scan starts at the 
        // most-recently-found/inserted slot - so multiple calls for the same metallicity hit on
        // the first comparison every time (typical access pattern in COMPAS during evolution of
        // a star/binary).  If we miss on the first scan, we perform the second scan - starting at
        // slot 0).  This way populated slots are visited at most once, and we only visit all
        // populated slots on a cache miss.
        //
        // Note that we have multiple exit points (return statements) in this function.  Ordinarily
        // we'd avoid that, but it saves CPU cycles - important here.

        // Scan part 1: m_LastFound .. end.
        // If the required metallicity is found, return the cache slot details.
        for (SizeT i = m_LastFound; i < m_CacheCount; ++i)
            if (std::abs(m_Keys[i] - p_Z) < Z_CACHE_TOL) { return i; }

        // Scan part 2: 0 .. m_LastFound.
        // We only fall through to here if the required metallicity was not found in the part 1
        // scan above.  If the required metallicity is found, return the cache slot details.
        for (SizeT i = 0; i < m_LastFound; ++i)
            if (std::abs(m_Keys[i] - p_Z) < Z_CACHE_TOL) { return i; }

        // Not found
        return std::nullopt;
    }


    // Small inline function to check if the Hurley struct is populated, and to
    // populate it if not - this function guarantees a populated Hurley struct.
    [[gnu::always_inline]] const ZDependentT& EnsureHurley(double p_Z) const {
        const SizeT slot = ResolveSlot(p_Z);
        if (!m_Cache[slot].Hurley.has_value())                                  // Hurley struct populated?
            [[unlikely]] CalculateHurleyForZ(p_Z, m_Cache[slot]);               // No - populate it
        return m_Cache[slot];                                                   // Guaranteed to have Hurley populated
    }

    // Small inline function to check if the Shikauchi struct is populated, and to
    // populate it if not - this function guarantees a populated Shikauchi struct.
    [[gnu::always_inline]] const ZDependentT& EnsureShikauchi(double p_Z) const {
        const SizeT slot = ResolveSlot(p_Z);
        if (!m_Cache[slot].Shikauchi.has_value())                               // Shikauchi struct populated?
            [[unlikely]] CalculateShikauchiForZ(p_Z, m_Cache[slot]);            // No - populate it
        return m_Cache[slot];                                                   // Guaranteed to have Shikauchi populated
    }


    /*
     * Values
     *
     * @brief
     * Returns the Z-dependent values for the given metallicity.
     * 
     * Looks p_Z up in the cache and, if found (cache hit), returns the cached entry.
     * If p_Z is not found (cache miss), calculates the values, inserts them into the
     * cache (with FIFO eviction if the cache is full), with key p_Z, and returns the
     * new entry.  The lookup and cache refresh are done by ResolveSlot().
     * 
     * The lookup of the cache key (p_Z) is performed with an absolute tolerance of
     * Z_CACHE_TOL - see constants.h.
     * 
     * 
     * const ZDependentT& Values(const double p_Z) const
     *
     * @param       p_Z                             Metallicity to look for in cache
     * @return                                      Const reference to the cached values for p_Z
     */
    [[gnu::always_inline]] const ZDependentT& Values(const double p_Z) const {
        return m_Cache[ResolveSlot(p_Z)];   // Return cached values
    }


    SizeT ResolveSlot(const double p_Z) const;

    void CalculateForZ(const double p_Z, ZDependentT& p_Slot) const;
    void CalculateHurleyForZ(const double p_Z, ZDependentT& p_Slot) const;
    void CalculateShikauchiForZ(const double p_Z, ZDependentT& p_Slot) const;

    GNU_PURE  HurleyACoeffsT       CalculateACoeffs_Hurley2000(const double p_Z, const double p_Sigma, const double p_Zeta) const;
    GNU_PURE  HurleyBCoeffsT       CalculateBCoeffs_Hurley2000(const double p_Z, const double p_Sigma, const double p_Zeta, const double p_Rho, const HurleyMassCutoffsT& p_MassCutoffs) const;
    GNU_PURE  HurleyAlphasT        CalculateAlphaConstants_Hurley2000(const double p_MHeF, const HurleyACoeffsT& p_aCoeffs, const HurleyBCoeffsT& p_bCoeffs) const;
    GNU_PURE  HurleyGConstsT       CalculateGammaConstants_Hurley2000(const HurleyACoeffsT& p_aCoeffs) const;
    GNU_PURE  HurleyLConstsT       CalculateLuminosityConstants_Hurley2000(const HurleyACoeffsT& p_aCoeffs) const;
    GNU_PURE  HurleyRConstsT       CalculateRadiusConstants_Hurley2000(const HurleyACoeffsT& p_aCoeffs) const;
    GNU_PURE  ShikauchiZDependentT CalculateCoeffs_Shikauchi2024(const double p_Z, const double p_logZ) const;
    GNU_CONST HurleyMassCutoffsT   CalculateMassCutoffs_Hurley2000(const double p_Z, const double p_Zeta) const;

    GNU_CONST double CalculateGBRadiusXExponent_Hurley2000(const double p_Zeta) const;
};
